/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AMap: typeof import('./src/components/map/AMap.vue')['default']
    ChunkFileUploader: typeof import('./src/components/chunkFileUploader/ChunkFileUploader.vue')['default']
    FileUpload: typeof import('./src/components/fileUpload/FileUpload.vue')['default']
    Folder: typeof import('./src/components/folder/Folder.vue')['default']
    GinPiece: typeof import('./src/components/gin-piece/GinPiece.vue')['default']
    HeaderAndSiderLayout: typeof import('./src/components/layout/headerAndSiderLayout/HeaderAndSiderLayout.vue')['default']
    HeaderLayout: typeof import('./src/components/layout/headerLayout/HeaderLayout.vue')['default']
    IconList: typeof import('./src/components/iconList/IconList.vue')['default']
    IconSelector: typeof import('./src/components/iconSelector/IconSelector.vue')['default']
    InfoWindow: typeof import('./src/components/map/InfoWindow.vue')['default']
    MediaList: typeof import('./src/components/Media/MediaList.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NP: typeof import('naive-ui')['NP']
    NPagination: typeof import('naive-ui')['NPagination']
    NProForm: typeof import('./src/components/n-pro-table/form/NProForm.vue')['default']
    NProTable: typeof import('./src/components/n-pro-table/NProTable.vue')['default']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLayout: typeof import('./src/components/layout/siderLayout/SiderLayout.vue')['default']
    StartMenu: typeof import('./src/components/startMenu/StartMenu.vue')['default']
    TableActions: typeof import('./src/components/tableActions/TableActions.vue')['default']
    VideoPlayer: typeof import('./src/components/videoPlayer/VideoPlayer.vue')['default']
  }
}
